# -*- coding: utf-8 -*-
"""Untitled190.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pnJjXxCcb2lCNWKCFm5yd8__kja0kFno
"""

!pip install -q git+https://github.com/openai/whisper.git

!pip install nemo_toolkit['asr']

import nemo.collections.asr as nemo_asr

print(nemo_asr.models.EncDecCTCModel.list_available_models())

!ffmpeg -i "/content/Quick Avatar Video.wav" -ac 1 -ar 16000 "/content/QuickAvatarMono.wav"

import nemo.collections.asr as nemo_asr

# Load pretrained ASR model
asr_model = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="stt_en_quartznet15x5")

# Transcribe
transcription = asr_model.transcribe(["/content/QuickAvatarMono.wav"])
print("Original Text:", transcription[0])

transcription

transcription[0]

!pip install transformers sentencepiece torch

text = transcription[0].text

from transformers import M2M100ForConditionalGeneration, M2M100Tokenizer

model_name = "facebook/m2m100_418M"
tokenizer = M2M100Tokenizer.from_pretrained(model_name)
model = M2M100ForConditionalGeneration.from_pretrained(model_name)

text_en = text

tokenizer.src_lang = "en"
encoded = tokenizer(text_en, return_tensors="pt")

generated_tokens = model.generate(**encoded, forced_bos_token_id=tokenizer.get_lang_id("hi"))
translated_text = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)[0]
print("Hindi Translation:\n", translated_text)

!pip install git+https://github.com/suno-ai/bark.git









